---
- name: Install Chrony
  apt:
    name: chrony
    state: present

- name: Configure Chrony
  template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    mode: 0644
  notify: restart chrony

- name: Set timezone
  timezone:
    name: Europe/Moscow